export interface SubscriptionMemberResponse {
  subscriptionMember: {
    id: number;
    userId: number;
    subscriptionId: number;
    subscriptionPeriodId: number;
    subscriptionPeriod: string;
    price: number;
    period: 'weekle' | 'monthly' | 'yearly';
    currency: 'rub' | 'eur';
    activatedAt: number;
    expiresAt: number;
    status: 'active' | string;
    paymentMethod: 'smart_glocal' | string;
    isDonate: boolean;
    isDeleted: boolean;
    isExpired: boolean;
    migrated: boolean;
    firstPeriodDiscountPercent: number;
    cancellationDiscountPercent: number;
    activePeriod: {
      id: number;
      period: string;
      amount: number;
      firstTimeDiscountEnabled: boolean;
      firstTimeDiscountPercent: number;
      cancellationDiscountEnabled: boolean;
      cancellationDiscountPercent: number;
      expiresAt: number;
    };
  };
  subscriptionPeriod: {
    id: number;
    period: 'weekle' | 'monthly' | 'yearly';
    amount: number;
    firstTimeDiscountEnabled: boolean;
    firstTimeDiscountPercent: number;
    cancellationDiscountEnabled: boolean;
    cancellationDiscountPercent: number;
    active: boolean;
  };
  subscription: {
    id: number;
    channelId: number;
    userId: number;
    image: null | string;
    name: string;
    description: string;
    currency: 'rub' | 'eur';
    trialPeriod: string;
    periods: null;
    deletedPeriods: null;
    buttonText: string;
    activeSubscribers: number;
    privateChannelInviteLink: string;
    publicChannelInviteLink: string;
    appInviteLink: string;
    webLink: string;
    isDeleted: boolean;
    isDonate: boolean;
    migrated: boolean;
    createdAt: number;
    acceptCards: boolean;
    acceptWalletPay: boolean;
    commentAccessEnabled: boolean;
  };
  channel: {
    id: number;
    type: 'public' | 'private';
    chatId: number;
    userId: number;
    name: string;
    userName: string;
    photoUrl: string;
    language: {
      code: string;
      name: string;
      englishName: string;
    };
    isDonationRequested: boolean;
    isOnboardingPassed: boolean;
    connected: boolean;
    activeSubscribers: number;
    allSubscribers: number;
    onboardingStep: 'completed';
    isDeleted: boolean;
    migrated: boolean;
    createdAt: number;
    isGroup: boolean;
    commentSubscriptionId: number;
    commentsAccessSubscription: {
      id: number;
      channelId: number;
      userId: number;
      image: null;
      name: string;
      description: string;
      currency: 'rub';
      trialPeriod: string;
      periods: null;
      deletedPeriods: null;
      buttonText: string;
      activeSubscribers: number;
      privateChannelInviteLink: string;
      publicChannelInviteLink: string;
      appInviteLink: string;
      webLink: string;
      isDeleted: boolean;
      isDonate: boolean;
      migrated: boolean;
      createdAt: number;
      acceptCards: boolean;
      acceptWalletPay: boolean;
      commentAccessEnabled: boolean;
    };
    ymAdEnabled: boolean;
  };
  user: {
    id: number;
    telegramId: number;
    firstName: string;
    lastName: string;
    userName: string;
    sex: number;
    hiddenSex: number;
    lang: string;
    banned: boolean;
    withdrawalBanned: boolean;
    migrated: boolean;
    createdAt: number;
    photoUrl: string;
    creator: boolean;
    adult: boolean;
    fromWeb: boolean;
    connectedToTelegram: boolean;
    payoutDestination: 'all' | string;
  };
}
