export type Transaction = {
  amount: number;
  channel: {
    chatId: number;
    id: number;
    isDeleted: boolean;
    isGroup: boolean;
    name: string;
    photoUrl: string;
    userName: string;
  };
  channelId: number;
  createdAt: number;
  currency: 'rub' | 'eur';
  donationRequestId: number;
  energy: number;
  id: number;
  objectId: number;
  otherUserId: number;
  paymentMethod: 'smart_glocal';
  serviceFee: number;
  subscription: {
    id: number;
    channelId: number;
    name: string;
    description: ' ';
    period: string;
    currency: 'rub' | 'eur';
    periods: null;
    inviteLink: string;
    appInviteLink: string;
    isDonate: boolean;
    isDeleted: boolean;
    acceptCards: boolean;
    acceptWalletPay: boolean;
    userID: number;
    commentAccessEnabled: boolean;
    image: null;
  };
  subscriptionMember: {
    id: number;
    userId: number;
    subscriptionId: number;
    subscriptionPeriodId: number;
    subscriptionPeriod: string;
    price: number;
    period: 'monthly' | 'yearly';
    currency: 'rub' | 'eur';
    activatedAt: number;
    expiresAt: number;
    status: 'active';
    paymentMethod: 'smart_glocal';
    isDonate: boolean;
    isDeleted: boolean;
    isExpired: boolean;
    migrated: boolean;
    firstPeriodDiscountPercent: number;
    cancellationDiscountPercent: number;
    activePeriod: {
      id: number;
      period: string;
      amount: number;
      firstTimeDiscountEnabled: boolean;
      firstTimeDiscountPercent: number;
      cancellationDiscountEnabled: boolean;
      cancellationDiscountPercent: number;
      expiresAt: number;
    };
  };
  subscriptionPeriod: {
    id: number;
    period: 'monthly' | 'yearly';
    amount: number;
    firstTimeDiscountEnabled: boolean;
    firstTimeDiscountPercent: number;
    cancellationDiscountEnabled: boolean;
    cancellationDiscountPercent: number;
    active: boolean;
  };
  total: number;
  type: 'sell_subscription_with_period';
  user: {
    id: number;
    firstName: string;
    lastName: string;
    userName: string;
    sex: number;
    photoUrl: string;
    telegramId: number;
  };
};
